
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retailstore-deployment
  namespace: retailstore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: retailstore
  template:
    metadata:
      labels:
        app: retailstore
    spec:
      containers:
      - name: retailstore
        image: yourusername/yourimage:tag
        ports:
        - containerPort: 80

