---
apiVersion: v1
kind: Service
metadata:
  name: retailstore-service
  namespace: retailstore
spec:
  selector:
    app: net-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
```
